import type { Metadata } from "next";
import { Merienda } from "next/font/google";
import Providers from "./_providers";
import { FC, Suspense } from "react";
import Loading from "./loading";

const inter = Merienda({ subsets: ["latin"] });

export interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout