import type { Metadata } from "next";
import { Lora, Merienda, Quicksand } from "next/font/google";
import Providers from "./_providers";
import { FC, Suspense } from "react";
import Loading from "./loading";

const fontFamily = Quicksand({ subsets: ["latin"] });

export interface LayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Merienda:wght@300..900&family=Quicksand:wght@300..700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <Providers>
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout